name: Tlog CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    # Cleanup workaround https://github.com/actions/checkout/issues/211
    - name: cleanup
      run: sudo chown -R justin:justin /home/justin/actions-runner/_work/tlog
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf -if
    - name: configure
      run: ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
    - name: make
      run: make
    - name: make check
      run: make check
    - name: sudo make install
      run: sudo make install
    - name: permission setup
      run: sudo chown tlog:tlog /usr/bin/tlog-rec-session
    - name: permission setup
      run: sudo chmod u+s /usr/bin/tlog-rec-session
    - name: permission setup
      run: sudo chmod g+s /usr/bin/tlog-rec-session
    - name: permission setup
      run: sudo chown tlog:utmp /var/run/tlog
    - name: intg tests
      run: sudo src/tlitest/tlitest-run
